extends Node

var texts := {
	"eng": {
		"KILL_1": "EMPLOYEE DISABLED",
		"KILL_2": "HR HAS BEEN NOTIFIED",
		"KILL_3": "SUBJECT OUT OF OPERATION",
		"KILL_4": "ERROR 404: GUARD NOT FOUND",
		"KILL_5": "SUBJECT LOST WILL TO LIVE",
		"KILL_6": "INVESTMENT LOST",
		"KILL_7": "TRANSFERRED TO BIOLOGICAL WASTE",
		"KILL_8": "WARRANTY VOIDED",
		"KILL_9": "SOMEONE WILL HAVE TO CLEAN THAT",
		"KILL_10": "BADGE RETURNED",
		"KILL_11": "SECURITY BUDGET CUT",
		"KILL_12": "STATUS: VERY DEAD",
		"KILL_13": "EX-EMPLOYEE DETECTED",

		"KILL_14": "UGLY SCENE.",
		"KILL_15": "OOPS.",
		"KILL_16": "NOT MUCH LEFT.",
		"KILL_17": "THAT’S GONNA STAIN.",
		"KILL_18": "ANOTHER ONE?",
		"KILL_19": "HE TRIED.",
		"KILL_20": "WHAT A SHAME.",
		"KILL_21": "NOT ANYMORE.",
		"KILL_22": "THIS GOT PERSONAL.",

		"KILL_23": "HE HAD WEEKEND PLANS",
		"KILL_24": "THIS GOES IN THE REPORT",
		"KILL_25": "WRONG BUTTON WAS PRESSED",
		"KILL_26": "THE UNION WILL HEAR ABOUT THIS",
		"KILL_27": "FASTER THAN EVOLUTION",
		"KILL_28": "SCIENTISTS DISAPPOINTED",
		"KILL_29": "PLEASE DO NOT REPEAT (REPEAT)",
		"KILL_30": "SUCCESSFUL TEST (?)",
		"KILL_31": "THANK YOU FOR PARTICIPATING",
		"KILL_32": "PREMIUM SUBSCRIPTION CANCELLED"
	},

	"ptbr": {
		"KILL_1": "FUNCIONÁRIO DESLIGADO",
		"KILL_2": "RECURSOS HUMANOS NOTIFICADOS",
		"KILL_3": "COBAIA FORA DE OPERAÇÃO",
		"KILL_4": "ERRO 404: GUARDA NÃO ENCONTRADO",
		"KILL_5": "PACIENTE PERDEU O INTERESSE EM VIVER",
		"KILL_6": "INVESTIMENTO PERDIDO",
		"KILL_7": "SUJEITO ENCAMINHADO AO LIXO BIOLÓGICO",
		"KILL_8": "GARANTIA ANULADA",
		"KILL_9": "ALGUÉM VAI TER QUE LIMPAR ISSO",
		"KILL_10": "SUJEITO DEVOLVEU O CRACHÁ",
		"KILL_11": "ORÇAMENTO DE SEGURANÇA REDUZIDO",
		"KILL_12": "STATUS: BASTANTE MORTO",
		"KILL_13": "EX-COLABORADOR DETECTADO",

		"KILL_14": "COISA FEIA.",
		"KILL_15": "OPS.",
		"KILL_16": "NÃO SOBROU MUITO.",
		"KILL_17": "ISSO DEIXA MANCHA.",
		"KILL_18": "OUTRO?",
		"KILL_19": "ELE TENTOU.",
		"KILL_20": "QUE PENA.",
		"KILL_21": "NÃO MAIS.",
		"KILL_22": "FICOU PESSOAL.",

		"KILL_23": "ELE TINHA PLANOS PARA O FIM DE SEMANA",
		"KILL_24": "ISSO VAI NO RELATÓRIO",
		"KILL_25": "NÃO ERA ESSE O BOTÃO",
		"KILL_26": "O SINDICATO VAI OUVIR FALAR DISSO",
		"KILL_27": "MAIS RÁPIDO QUE A EVOLUÇÃO",
		"KILL_28": "CIENTISTAS DESAPONTADOS",
		"KILL_29": "FAVOR NÃO REPETIR (REPITA)",
		"KILL_30": "TESTE BEM-SUCEDIDO (?)",
		"KILL_31": "OBRIGADO POR PARTICIPAR",
		"KILL_32": "ASSINATURA PREMIUM CANCELADA"
	}
}

func get_text(key: String) -> String:
	return texts.get(Global.lingua, {}).get(key, "[MISSING UI TEXT: %s]" % key)
